# Generated by Django 3.0.1 on 2020-06-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200617_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teams',
            field=models.CharField(default="Jake's Team", max_length=100),
        ),
    ]
