# Generated by Django 3.0.1 on 2020-06-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teams_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='teams',
        ),
    ]
