# Generated by Django 3.0.1 on 2020-06-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200621_1344'),
        ('teams', '0004_remove_teams_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts'),
        ),
    ]
