# Generated by Django 3.0.1 on 2020-06-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20200623_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='sport',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
