# Generated by Django 3.0.1 on 2020-06-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_organisations_owner'),
        ('teams', '0008_auto_20200623_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='org',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrgsofTeam', to='organisation.Organisations'),
        ),
    ]
