# Generated by Django 3.0.1 on 2020-07-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_remove_competitions_teams'),
        ('teams', '0009_teams_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='TeamCompetiton',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Competitions'),
        ),
    ]
