# Generated by Django 3.0.1 on 2020-06-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20200617_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganisationName', models.CharField(default=None, max_length=100)),
                ('teams', models.ManyToManyField(to='teams.Teams')),
            ],
        ),
    ]
