# Generated by Django 3.0.1 on 2020-07-01 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20200701_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='CompetitionEndDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='competitions',
            name='CompetitionStartDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
