# Generated by Django 3.0.1 on 2020-07-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200630_2035'),
        ('organisation', '0007_auto_20200701_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='CompetitionDay',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='CompetitionEndTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='CompetitionGender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Either', 'Either')], default='Either', max_length=6),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='CompetitionGrade',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='CompetitionLocation',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='CompetitionOrganisation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisations'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='CompetitionSport',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='CompetitionStartTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='LengthOfGame',
            field=models.CharField(blank=True, default='1 hour', max_length=100),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts'),
        ),
    ]
