# Generated by Django 3.0.1 on 2020-07-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_auto_20200701_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitions',
            name='teams',
        ),
    ]
