# Generated by Django 3.0.1 on 2020-07-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_auto_20200702_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitions',
            name='CompetitionRegistrationLink',
        ),
        migrations.AddField(
            model_name='organisations',
            name='CompetitionRegistrationLink',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
