# Generated by Django 3.0.1 on 2020-06-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='accountName',
            field=models.CharField(default='NoNameMade', max_length=100),
        ),
    ]
