# Generated by Django 3.0.1 on 2020-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_accountname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='user',
            new_name='userInstance',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='accountName',
            field=models.CharField(default='NoNameMade', max_length=100, unique=True),
        ),
    ]
