# Generated by Django 3.0.1 on 2020-06-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200619_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='description',
            field=models.CharField(default='Hey! I love playing netball!', max_length=1000),
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(default='Anon', max_length=50),
        ),
        migrations.AddField(
            model_name='accounts',
            name='gender',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(default='Smith', max_length=50),
        ),
        migrations.AddField(
            model_name='accounts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
