# Generated by Django 3.0.1 on 2020-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200619_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='image',
            field=models.ImageField(blank=True, default='sharon.png', upload_to=''),
        ),
    ]
