# Generated by Django 3.0.1 on 2020-06-22 15:10

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_organisations_owner'),
        ('accounts', '0006_auto_20200621_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', django_mysql.models.ListCharField(models.CharField(max_length=20), default=None, max_length=147, size=7)),
                ('days', django_mysql.models.ListCharField(models.CharField(max_length=10), default=None, max_length=77, size=7)),
                ('EarliestTime', models.TimeField(default=None, null=True)),
                ('LatestTime', models.TimeField(default=None, null=True)),
                ('gender', models.CharField(default='Female', max_length=10)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('fakeColumn', models.CharField(default='', max_length=1000, null=True)),
                ('org', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisations')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts')),
            ],
        ),
    ]
