# Generated by Django 3.0.1 on 2020-07-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200705_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='FillIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='Permanent',
            field=models.BooleanField(default=False),
        ),
    ]
