# Generated by Django 3.0.1 on 2020-07-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200705_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='days',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='sport',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
    ]
