# Generated by Django 3.0.1 on 2020-07-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200707_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='last_name',
            field=models.CharField(default='Smith', max_length=50),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='ownerFirstName',
            field=models.CharField(default='Anon', max_length=50),
        ),
    ]
