# Generated by Django 3.0.1 on 2020-07-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200707_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisements',
            old_name='last_name',
            new_name='ownerLastName',
        ),
    ]
